### ISSUE TITLE
Bio limit warning

### ISSUE THREAD

**Issue by brooksbecton** [thebetternewt/gcp-marketplace-react#4]
When creating a profile there is a 300 character limit for the bio. We should atleast put this under the bio to the user's know, and it would also be good to have a character counter for that section. 

I had put in some text, hit submit and it looked like nothing happened. I checked the console to see that there was an error and then scrolled up to see that there was a red error under the bio. Because of this, we should also scroll the error into view or add a message under the submit that lets a user know they've had errors and that they should correct them. 

- [x] Add message about 300 character limit on the bio
- [x] Add character counter on the bio input (Maybe check and warn as a user is typing)
- [x] Add error under the submit button to display if there are any errors

**Comment by thebetternewt** [comment]
Working on this...

**Comment by thebetternewt** [comment]
Added counter and moved form elements to the UI folder to share across components. Still need to add error under submit button.
